### PR TITLE
Updated Device Name to Device Network ID, also remember last state

### PR DESCRIPTION
**Pull request by itsamti**
Hi Becky, You gave new direction and your work was deciding factor to go with Broadlink. Thanks!

I updated your code to use Device Network Id. Also changed switch type to also have physical switch as well as it now remembers the last status in ST.

Please review and and you may create new code file and add in your repository.

### CODE REVIEW

**Comment by beckyricha** [comment]
Thanks!  Have you confirmed the device id is working? I started that way originally but my hub would never process the command. This is why I decided on using the name instead.

The other code for the state seems a bit more complex so i will need to review it later but will do it soon.  I really appreciate being able to track the state as i didn't have time to think about that yet.  

Thanks again. I was hoping this basic start would have others making it better like this.

On September 1, 2016 11:21:24 PM EDT, itsamti <notifications@github.com> wrote:
>Hi Becky, You gave new direction and your work was deciding factor to
>go with Broadlink. Thanks!
>
>I updated your code to use Device Network Id. Also changed switch type
>to also have physical switch as well as it now remembers the last
>status in ST.
>
>Please review and and you may create new code file and add in your
>repository.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/beckyricha/Broadlink-RM-SmartThings-Alexa/pull/3
>
>-- Commit Summary --
>
>  * Updated Device Name to Device Network ID
>  * Updated code to use Device ID and remember last state
>
>-- File Changes --
>
>    M Broadlink RM Bridge Switch LAN (76)
>
>-- Patch Links --
>
>https://github.com/beckyricha/Broadlink-RM-SmartThings-Alexa/pull/3.patch
>https://github.com/beckyricha/Broadlink-RM-SmartThings-Alexa/pull/3.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beckyricha/Broadlink-RM-SmartThings-Alexa/pull/3

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by itsamti** [comment]
Thanks for getting back. Device Network id is working flawless. 

Another thing, I even tested device state with Alexa. All switches are showing right state (On/Off) based on what you do in IFTTT.

**Comment by beckyricha** [comment]
Would you please clarify? What does ifttt have to do with it?


On September 2, 2016 8:43:03 AM EDT, itsamti <notifications@github.com> wrote:
>Thanks for getting back. Device Network id is working flawless. 
>
>Another thing, I even tested device state with Alexa. All switches are
>showing right state (On/Off) based on what you do in IFTTT.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/beckyricha/Broadlink-RM-SmartThings-Alexa/pull/3#issuecomment-244364393

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by itsamti** [comment]
Good Question :) . I was not aware that i can integrated Alexa directly with smartthings.  I had integrated alexa to smartthings via IFTTT until this morning.

**Comment by beckyricha** [comment]
Actually, ignore questions above.  I took a closer look at the version before the delays were added and I see what it is trying to do.  It does offer some good features.  I hope you don't mind, but I am adding a few clarifying comments here for those who may have some value in this version instead of the original, to help until I can get it merged: 

1. Smartthings seems to have fixed a few things that frustrated me, so you can now use the device ID instead of the device name (this and the supposedly functional delay options did not work for me a few months ago, so I'm glad ST is staying on this stuff).  If using this version, you will need to name your codes/devices differently than described in the master readme.  You now need to match the name you use when programming the RM Bridge app to your SmartThings device id, not the device name.  Make sure to use a unique device id for each device.  Go to the main readme in my branch for explanation of this.

2. Before deciding, it is important to know exactly what this is for. This changes nothing related to Alexa or the way your devices physically behave, so if you already have your devices working and that is what you needed it for, this is likely not worth your time because you will have to change those device setups.  It changes things only in the smart things app, and maybe any other services out there that rely on ST communication about device state.  It now keeps track of the last command sent by smart things to turn your device on or off.  It doesn't actually know if your device is on or off, but does offer you a way to get these back in sync if they get messed up, without having to reach for your remote control.  This is what the onPhysical and offPhysical commands I asked about earlier are for.  The name is an artifact of using a different ST switch type, and is not related to whether or not your switch is "physical" or "virtual."  Don't worry about that when deciding whether to use this.

3. Where this really shines is for getting devices back in sync in the ST app if the state doesn't match, and that unresolved possibility is one reason I had not bothered with state tracking previously.  When you open this version of the device in the ST app it shows the main on/off state like most devices do, on a switch that you touch to reverse the device state.  However, next to that this version also adds buttons labeled on and off.  So if your device already says it is on but isn't really, you can easily resend that on command again, without changing its tracked state to "off" or first sending the "off" command as it did before.  If you are only using alexa and not the ST app, you can already effectively do this by simply repeating the "on" or "off" command that didn't work.

This seems to work without issues, and all instructions are as in the readme except how to name your devices/device ID as described above.  I will get this into the master version soon but need to do it when I have time to update the readme accordingly and remove some commented code sections that are not needed here.

**Comment by itsamti** [comment]
Thank you!

**Comment by beckyricha** [comment]
One more minor note so people don't think there is an issue.  When you first install this to a device, it will show a state of "0" instead of on or off.  That just means it does not know the state of your device yet.  As soon as you turn each device on or off the status will update and the switches will look right.  I'm just guessing, but I imagine the same could happen later if there is ever a glitch or reset needed with your hub and it forgets the state, but it's an easy update and not a problem with the app.

**Comment by itsamti** [comment]
Yes, I also realized that. But its just first time so should be fine.

**Comment by beckyricha** [comment]
I manually incorporated these changes.  Thanks for the input!

**Pull request closed without merging**
